data_accuracy:
  name: "Data Accuracy"
  icon: "microscope"
  description: "Errors in raw or interim data which need to be checked"
  examples:
  - "Number of rows in a joined table looks like a fan out issue"
methods:
  name: "Correctness of Approach"
  icon: "crystal_ball"
  description: "Issues in the approach or methods selected that may be a problem for the analysis"
  examples:
  - "The analyst used a linear regression on a binary outcome variable"
results_accuracy:
  name: "Results Accuracy"
  icon: "telescope"
  description: "Problems or unexpected outcomes in the results from analyses"
  examples:
  - "Predictions in the out-of-sample period are greater than 10X all prior data for subgroup A"
results_completeness:
  name: "Results Completeness"
  icon: "gem"
  description: "Expected outputs or figures are not produced that will be needed"
  examples:
  - "No histograms provided in exploratory analysis notably no visuals of missingness to help us understand whether this is an issue."
reproducibility:
  name: "Reproducibility"
  icon: "ledger"
  description: "The reviewer is struggling to reproduce core parts of the analysis"
  examples:
  - "When knitting an rmarkdown it produces an error on my computer"
coding_practices:
  name: "Coding Practices"
  icon: "art"
  description: "Coding practices or following of good standards that can be fixed"
  examples:
  - "A long script is built in which the same pieces are used repeatedly. Turn these into functions to prevent errors"
readability:
  name: "Readability"
  icon: "book"
  description: "Lack of commenting or struggling to understand code-as-written"
  examples:
  - "I don't understand what you're trying to do with lines 200 - 250. What does this mean?"
performance:
  name: "Performance"
  icon: "hourglass"
  description: "Improving how long something takes to run or general optimizations"
  examples:
  - "If you switch from running this in a loop to using vectorized code it will make the function run faster."
documentation:
  name: "Documentation"
  icon: "pencil"
  description: "Ensuring that code especially completed projects are well documented"
  examples:
  - "The README for the project is outdated. Can you update to explain the decisions we made and why?"
suggestion:
  name: "Enhancement Opportunities"
  icon: "school_satchel"
  description: "Opportunites or suggestions to improve the way someone accomplished something."
  examples:
  - "If you used the leaflet library you may be able to make your map interactive and easier to share instead of static."
ideas:
  name: "Alternatives to Consider"
  icon: "bulb"
  description: "Ideas for a different approach or new analyses."
  examples:
  - "Using tSNE and other dimensionality reduction techniques first may improve the clusters you've created or at least help with visualizing them and how close/separated they are."
